# Ch `02`: Concept `01`

## Defining tensors

ops用来重置网络

Import TensorFlow and Numpy:

In [1]:
import tensorflow as tf
from tensorflow.python.framework import ops
ops.reset_default_graph()

import numpy as np

Now, define a 2x2 matrix in different ways:

In [2]:
m1 = [[1.0, 2.0], 
      [3.0, 4.0]]

m2 = np.array([[1.0, 2.0], 
               [3.0, 4.0]], dtype=np.float32)

m3 = tf.constant([[1.0, 2.0], 
                  [3.0, 4.0]])

Let's see what happens when we print them:

In [3]:
print(type(m1))
print(type(m2))
print(type(m3))

<type 'list'>
<type 'numpy.ndarray'>
<class 'tensorflow.python.framework.ops.Tensor'>


So, that's what we're dealing with. Interesting. 

By the way, there's a function called `convert_to_tensor(...)` that does exactly what you might expect. 

Let's use it to create tensor objects out of various types:

In [4]:
t1 = tf.convert_to_tensor(m1, dtype=tf.float32)
t2 = tf.convert_to_tensor(m2, dtype=tf.float32)
t3 = tf.convert_to_tensor(m3, dtype=tf.float32)

Ok, ok! Time for the reveal:

In [5]:
print(type(t1))
print(type(t2))
print(type(t3))

<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>


## 2 创建tensor

### 2.1 tf.zeros()

In [15]:
sess = tf.InteractiveSession()
my_tensor = tf.zeros([1,20])
sess.run(my_tensor)

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.]], dtype=float32)

In [8]:
### 2.2 tf.ones()

In [9]:
my_tensor = tf.ones([1,20])
sess.run(my_tensor)

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.]], dtype=float32)

### 3 placeholder占位符

In [18]:
x = tf.placeholder(tf.float32, shape=(4, 4))
rand_array = np.random.rand(4, 4)
rand_array

array([[ 0.16796738,  0.78915443,  0.54424564,  0.61407587],
       [ 0.59536831,  0.81487717,  0.2559398 ,  0.30419123],
       [ 0.32773651,  0.26386584,  0.35326486,  0.77263069],
       [ 0.0150011 ,  0.0954362 ,  0.66943417,  0.07670334]])

In [19]:
y = tf.identity(x)
# Print the output, feeding the value of x into the computational graph
print(sess.run(y, feed_dict={x: rand_array}))

[[ 0.16796738  0.78915441  0.54424566  0.6140759 ]
 [ 0.59536833  0.81487715  0.25593981  0.30419123]
 [ 0.32773653  0.26386583  0.35326487  0.77263069]
 [ 0.0150011   0.0954362   0.66943419  0.07670333]]


# 关闭session

In [ ]:
sess.close()