# Ch `02`: Concept `05`

## Using variables

Here we go, here we go, here we go! Moving on from those simple examples, let's get a better understanding of variables. Start with a session:

In [2]:
import tensorflow as tf
from tensorflow.python.framework import ops
ops.reset_default_graph()
sess = tf.InteractiveSession()

Below is a series of numbers. Don't worry what they mean. Just for fun, let's think of them as neural activations.

In [2]:
raw_data = [1., 2., 8., -1., 0., 5.5, 6., 13]

## 1 初始化逻辑变量

Create a boolean variable called `spike` to detect a sudden increase in the values.

All variables must be initialized. Go ahead and initialize the variable by calling `run()` on its `initializer`:

所有变量必须初始化，初始化的变量通过`run`来初始化

In [3]:
spike = tf.Variable(False)
spike.initializer.run()

Loop through the data and update the spike variable when there is a significant increase:

In [4]:
for i in range(1, len(raw_data)):
    if raw_data[i] - raw_data[i-1] > 5:
        updater = tf.assign(spike, tf.constant(True))
        updater.eval()
    else:
        tf.assign(spike, False).eval()
    print("Spike", spike.eval())

Spike False
Spike True
Spike False
Spike False
Spike True
Spike False
Spike True


## 2 初始化0 或 1变量

In [3]:
row_dim = 2
col_dim = 3
zero_var = tf.Variable(tf.zeros([row_dim, col_dim]))
ones_var = tf.Variable(tf.ones([row_dim, col_dim]))

In [4]:
sess.run(zero_var.initializer)
sess.run(ones_var.initializer)
print(sess.run(zero_var))
print(sess.run(ones_var))

[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]]


## 3 利用相似的shape创建变量tf.zeros_like， tf.ones_like

In [5]:
zero_similar = tf.Variable(tf.zeros_like(zero_var))
ones_similar = tf.Variable(tf.ones_like(ones_var))

sess.run(ones_similar.initializer)
sess.run(zero_similar.initializer)
print(sess.run(ones_similar))
print(sess.run(zero_similar))

[[ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]]


## 4 用填充值tf.fill初始化变量 

In [6]:
fill_var = tf.Variable(tf.fill([row_dim, col_dim], -1))
sess.run(fill_var.initializer)
print(sess.run(fill_var))

[[-1 -1 -1]
 [-1 -1 -1]]


## 5 用常数tensor初始化变量

In [7]:
# Create a variable from a constant
const_var = tf.Variable(tf.constant([8, 6, 7, 5, 3, 0, 9]))
# This can also be used to fill an array:
const_fill_var = tf.Variable(tf.constant(-1, shape=[row_dim, col_dim]))

sess.run(const_var.initializer)
sess.run(const_fill_var.initializer)

print(sess.run(const_var))
print(sess.run(const_fill_var))

[8 6 7 5 3 0 9]
[[-1 -1 -1]
 [-1 -1 -1]]


## 6 构建序列，初始化变量

In [8]:
linear_var = tf.Variable(tf.linspace(start=0.0, stop=1.0, num=3)) # Generates [0.0, 0.5, 1.0] includes the end

# Range in TensorFlow
sequence_var = tf.Variable(tf.range(start=6, limit=15, delta=3)) # Generates [6, 9, 12] doesn't include the end

sess.run(linear_var.initializer)
sess.run(sequence_var.initializer)

print(sess.run(linear_var))
print(sess.run(sequence_var))

[ 0.   0.5  1. ]
[ 6  9 12]


## 7 随机初始化变量

In [9]:
rnorm_var = tf.random_normal([row_dim, col_dim], mean=0.0, stddev=1.0)
runif_var = tf.random_uniform([row_dim, col_dim], minval=0, maxval=4)

print(sess.run(rnorm_var))
print(sess.run(runif_var))

[[ 0.03124509  0.35925102 -1.44186771]
 [ 0.12090629 -0.38777757 -0.22917119]]
[[ 1.98120499  3.37225628  0.34650707]
 [ 3.65330553  2.12447834  0.966537  ]]


In [ ]:
sess.close()

## 8 TensorBoard可视化创建的变量

执行：

tensorboard --logdir=/tmp/variable_logs

查看：

http://0.0.0.0:6006/

In [11]:
# 重设网络
ops.reset_default_graph()

# Start a graph session
sess = tf.Session()

# Create variable
my_var = tf.Variable(tf.zeros([1,20]))

# Add summaries to tensorboard
merged = tf.summary.merge_all()

# Initialize graph writer:
writer = tf.summary.FileWriter("/tmp/variable_logs", graph=sess.graph)

# Initialize operation
initialize_op = tf.global_variables_initializer()

# Run initialization of variable
sess.run(initialize_op)

不要忘记关闭session

You forgot to close the session! Here, let me do it:

In [12]:
sess.close()