In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.python.framework import ops
ops.reset_default_graph()

# 开启Session

In [2]:
sess = tf.Session()

# 1 创建矩阵

## 1.1 创建单位矩阵

In [4]:
identity_matrix = tf.diag([1.0,1.0,1.0])
print(sess.run(identity_matrix))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


## 1.2 正态分布抽样的矩阵 

In [6]:
A = tf.truncated_normal([2,3])
print(sess.run(A))

[[ 0.  0.  0.]
 [ 0.  0.  0.]]


## 1.3 用常数填充矩阵

In [8]:
B = tf.fill([2,3], 5.0)
print(sess.run(B))

[[ 5.  5.  5.]
 [ 5.  5.  5.]]


## 1.4 均匀分布抽样的矩阵

In [18]:
C = tf.random_uniform([3,2])
print(sess.run(C))

[[ 0.35675347  0.67275882]
 [ 0.74676108  0.20942366]
 [ 0.85412645  0.54593503]]


## 1.5 用numpy创建的矩阵，转化为tensor矩阵

In [10]:
D = tf.convert_to_tensor(np.array([[1., 2., 3.], [-3., -7., -1.], [0., 5., -2.]]))
print(sess.run(D))

[[ 1.  2.  3.]
 [-3. -7. -1.]
 [ 0.  5. -2.]]


# 2 矩阵的操作

## 2.1 加法

In [13]:
print(sess.run(A+B))
print(sess.run(B-B))

[[ 4.9775238   5.94863129  4.65811396]
 [ 4.93201256  5.87034941  5.06973362]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]]


## 2.2 矩阵点积

In [15]:
print(sess.run(tf.matmul(B, identity_matrix)))

[[ 5.  5.  5.]
 [ 5.  5.  5.]]


## 2.3 转置

In [19]:
print(sess.run(tf.transpose(C)))

[[ 0.53690004  0.35271728  0.41912997]
 [ 0.76825261  0.97233295  0.80831552]]


## 2.4 求行列式

In [21]:
sess.run(tf.matrix_determinant(D))

-37.999999999999993

## 2.5 矩阵的逆

In [23]:
print(sess.run(tf.matrix_inverse(D)))

[[-0.5        -0.5        -0.5       ]
 [ 0.15789474  0.05263158  0.21052632]
 [ 0.39473684  0.13157895  0.02631579]]


## 2.6 cholesky分解
Cholesky 分解是把一个对称正定的矩阵表示成一个下三角矩阵L和其转置的乘积的分解。它要求矩阵的所有特征值必须大于零，故分解的下三角的对角元也是大于零的

In [26]:
print(sess.run(tf.cholesky(identity_matrix)))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


## 2.7 奇异值分解

In [29]:
eigenvalues, eigenvectors = sess.run(tf.self_adjoint_eig(D))
print(eigenvalues)
print(eigenvectors)

[-10.65907521  -0.22750691   2.88658212]
[[ 0.21749542  0.63250104 -0.74339638]
 [ 0.84526515  0.2587998   0.46749277]
 [-0.4880805   0.73004459  0.47834331]]


# 关闭session

In [31]:
sess.close()